### ISSUE TITLE
Dont work in December  !!!! ????

### ISSUE THREAD

**Issue by marcoas** [padolsey/cron.js#2]
In my tests don't work only for December.

I change this line 
this.constraints = [[0,59],[0,59],[0,23],[1,31],[0,11],[1,7]];

for thi one
this.constraints = [[0,59],[0,59],[0,23],[1,31],[1,12],[1,7]];

and work now !

It's correct ? or maybe there are more changes to do ?

**Comment by padolsey** [comment]
Thanks for reporting this! https://github.com/jamespadolsey/cron.js/commit/f6a41b99b4b7f10da89ca8c0ea6081b531fec101
